### Generate Token
# @name generateToken
POST /users/generateToken HTTP/1.1
Host: localhost:3000

###
@authToken = Bearer {{generateToken.response.body.token}}

### Get Profile
GET /users/profile HTTP/1.1
Host: localhost:3000
Authorization: {{authToken}}

### Get All Posts
GET /posts HTTP/1.1
Host: localhost:3000
Authorization: {{authToken}}

### Add New Posts
POST /posts HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Content-Length: 126
Authorization: {{authToken}}

{
    "title": "Six Post",
    "description": "This is my six posts",
    "author": "saptarga",
    "email": "saptarga@gmail.com"
}

### Get Specific Posts
GET /posts/60ed7ab79e72ea5fdc36d9b5 HTTP/1.1
Host: localhost:3000
Authorization: {{authToken}}