@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxNjI2NTE0NTc3MDYzLCJ1c2VybmFtZSI6InNhcHRhcmdhIiwiZW1haWwiOiJzYXB0YXJnYUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMzQ1Njc4OTAxIn0sImlhdCI6MTYyNjUxNDU3NywiZXhwIjoxNjI3MTE5Mzc3fQ.sK6BN9CGLsIyFCBLNFV9CjWHF2_qcHlCjp-L0S_kZyQ

### Generate Token
POST /users/generateToken HTTP/1.1
Host: localhost:3000

### Get Profile
GET /users/profile HTTP/1.1
Host: localhost:3000
Authorization: {{token}}

### Get All Posts
GET /posts HTTP/1.1
Host: localhost:3000
Authorization: {{token}}

### Add New Posts
POST /posts HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Content-Length: 126
Authorization: {{token}}

{
    "title": "Six Post",
    "description": "This is my six posts",
    "author": "saptarga",
    "email": "saptarga@gmail.com"
}

### Get Specific Posts
GET /posts/60f2547141795117f83b1593 HTTP/1.1
Host: localhost:3000
Authorization: {{token}}